//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Management.Entity.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Management.Entity.Properties.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avatar-sample.jpg.
        /// </summary>
        public static string AvatarUserDefault {
            get {
                return ResourceManager.GetString("AvatarUserDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \~Temp\FileImage\AvatarUser\.
        /// </summary>
        public static string DirectoryImage {
            get {
                return ResourceManager.GetString("DirectoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới không thành công.
        /// </summary>
        public static string ErrorAddEntity {
            get {
                return ResourceManager.GetString("ErrorAddEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thể loại sách không tồn tại.
        /// </summary>
        public static string ErrorBookCategory {
            get {
                return ResourceManager.GetString("ErrorBookCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại sách không hợp lệ hoặc đã tồn tại, vui lòng thử lại..
        /// </summary>
        public static string ErrorBookCategoryExist {
            get {
                return ResourceManager.GetString("ErrorBookCategoryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sách không hợp lệ hoặc đã tồn tại, vui lòng thử lại..
        /// </summary>
        public static string ErrorBookExist {
            get {
                return ResourceManager.GetString("ErrorBookExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể đổi mật khẩu, vui lòng thử lại..
        /// </summary>
        public static string ErrorConfirmOTPPassWord {
            get {
                return ResourceManager.GetString("ErrorConfirmOTPPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu không thành công.
        /// </summary>
        public static string ErrorDeleteEntity {
            get {
                return ResourceManager.GetString("ErrorDeleteEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy dữ liệu, vui lòng thử lại..
        /// </summary>
        public static string ErrorNotIDEntity {
            get {
                return ResourceManager.GetString("ErrorNotIDEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP không chính xác, vui lòng thử lại..
        /// </summary>
        public static string ErrorOTPCode {
            get {
                return ResourceManager.GetString("ErrorOTPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công.
        /// </summary>
        public static string ErrorUpdateEntity {
            get {
                return ResourceManager.GetString("ErrorUpdateEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại, vui lòng thử lại..
        /// </summary>
        public static string ErrorUserAccount {
            get {
                return ResourceManager.GetString("ErrorUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        public static string ErrorUserAccountValidate {
            get {
                return ResourceManager.GetString("ErrorUserAccountValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thất bại.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản hoặc địa chỉ email đã tồn tại, vui lòng thử lại..
        /// </summary>
        public static string IsExistUserAccount {
            get {
                return ResourceManager.GetString("IsExistUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ email đã được sử dụng, vui lòng thử lại..
        /// </summary>
        public static string IsUsedEmail {
            get {
                return ResourceManager.GetString("IsUsedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meom7646@gmail.com.
        /// </summary>
        public static string MailSendAccount {
            get {
                return ResourceManager.GetString("MailSendAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aa9685354.
        /// </summary>
        public static string MailSendPassWord {
            get {
                return ResourceManager.GetString("MailSendPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi không tìm thấy dữ liệu.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Library Management&lt;/b&gt;: Mã xác thực OTP của tài khoản &lt;b&gt;{0}&lt;/b&gt; là &lt;b&gt;{1}&lt;/b&gt;. Bạn đang thực hiện &lt;b&gt;{2}&lt;/b&gt; trên hệ thống Library, mật khẩu mới là &lt;b&gt;{3}&lt;/b&gt;..
        /// </summary>
        public static string SubjectSendMail {
            get {
                return ResourceManager.GetString("SubjectSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành công.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi validate dữ liệu không hợp lệ.
        /// </summary>
        public static string ValidateEntity {
            get {
                return ResourceManager.GetString("ValidateEntity", resourceCulture);
            }
        }
    }
}
